version: '3.8'

networks:
  traefik-network:
    name: ${TRAEFIK_NETWORK}

# Import service definitions from separate files
include:
  - ./traefik/traefik-compose.yaml
  - ./gitlab/gitlab-compose.yaml  
  - ./whoami/whoami-compose.yaml