api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik-network

entryPoints:
  web:
    address: ":80"

log:
  level: INFO

accessLog: {}
