# Static configuration
api:
  insecure: true  # Enable the API and dashboard
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

# Configure providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik-network

# TLS Configuration
tls:
  certificates:
    - certFile: /certs/gitlab.crt
      keyFile: /certs/gitlab.key

# Define security headers middleware
http:
  middlewares:
    securityHeaders:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
  
  # Router for Traefik dashboard
  routers:
    dashboard:
      rule: "Host(`${TRAEFIK_DASHBOARD_HOST}`)"
      service: "api@internal"
      entryPoints:
        - web

log:
  level: INFO