version: '3.8'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: always
    hostname: '${GITLAB_HOSTNAME}'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${GITLAB_HOSTNAME}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT}
        
        # SMTP Configuration using environment variables
        gitlab_rails['smtp_enable'] = ${SMTP_ENABLED}
        gitlab_rails['smtp_address'] = "${SMTP_ADDRESS}"
        gitlab_rails['smtp_port'] = ${SMTP_PORT}
        gitlab_rails['smtp_user_name'] = "${SMTP_USER}"
        gitlab_rails['smtp_password'] = "${SMTP_PASSWORD}"
        gitlab_rails['smtp_domain'] = "${SMTP_DOMAIN}"
        gitlab_rails['smtp_authentication'] = "${SMTP_AUTH}"
        gitlab_rails['smtp_enable_starttls_auto'] = ${SMTP_STARTTLS}
        gitlab_rails['smtp_tls'] = ${SMTP_TLS}
        gitlab_rails['gitlab_email_from'] = "${SMTP_FROM}"
        gitlab_rails['gitlab_email_reply_to'] = "${SMTP_REPLY_TO}"
    ports:
      - '${GITLAB_HTTP_PORT}:80'
      - '${GITLAB_HTTPS_PORT}:443'
      - '${GITLAB_SSH_PORT}:22'
    volumes:
      - '${GITLAB_PERSISTENCE}/config:/etc/gitlab'
      - '${GITLAB_PERSISTENCE}/logs:/var/log/gitlab'
      - '${GITLAB_PERSISTENCE}/data:/var/opt/gitlab'
    shm_size: '256m'

networks:
  default:
    name: gitlab_network
