version: '3.8'

networks:
  traefik-network:
    name: traefik-network

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"     # HTTP
      - "8080:8080" # Dashboard
    networks:
      - traefik-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/config:/etc/traefik
    command:
      - "--configFile=/etc/traefik/traefik.yaml"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.homelab.lan`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=web"
      
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: always
    hostname: 'gitlab.homelab.lan'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://gitlab.homelab.lan"
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT}

        # Disable internal NGINX since Traefik will handle HTTP traffic
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        
        # Allow Traefik to communicate with GitLab
        nginx['client_max_body_size'] = '250m'

        # -----------------------------
        # SMTP Configuration
        # -----------------------------
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "${SMTP_ADDRESS}"
        gitlab_rails['smtp_port'] = ${SMTP_PORT}
        gitlab_rails['smtp_user_name'] = "${SMTP_USER}"
        gitlab_rails['smtp_password'] = "${SMTP_PASSWORD}"
        gitlab_rails['smtp_domain'] = "${SMTP_DOMAIN}"
        gitlab_rails['smtp_authentication'] = "${SMTP_AUTH}"
        gitlab_rails['smtp_enable_starttls_auto'] = ${SMTP_STARTTLS}
        gitlab_rails['smtp_tls'] = ${SMTP_TLS}
        gitlab_rails['gitlab_email_from'] = "${SMTP_FROM}"
        gitlab_rails['gitlab_email_reply_to'] = "${SMTP_REPLY_TO}"
    networks:
      - traefik-network
    ports:
      - '${GITLAB_SSH_PORT}:22'  # SSH traffic goes directly to GitLab
    volumes:
      - '${GITLAB_PERSISTENCE}/config:/etc/gitlab'
      - '${GITLAB_PERSISTENCE}/logs:/var/log/gitlab'
      - '${GITLAB_PERSISTENCE}/data:/var/opt/gitlab'
    shm_size: '256m'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.homelab.lan`)"
      - "traefik.http.routers.gitlab.entrypoints=web"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"