version: '3.8'

networks:
  traefik-network:
    name: ${TRAEFIK_NETWORK}

# Import service definitions from separate files
include:
  - ./compose/traefik/traefik-compose.yaml
  - ./compose/gitlab/gitlab-compose.yaml  
  - ./compose/whoami/whoami-compose.yaml