version: '3.8'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:17.10.1-ce.0'
    container_name: gitlab
    restart: always
    hostname: '${GITLAB_HOSTNAME}'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "https://${GITLAB_HOSTNAME}"
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT}
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        # -----------------------------
        # SMTP Configuration
        # -----------------------------
        gitlab_rails['smtp_enable'] = ${SMTP_ENABLED}
        gitlab_rails['smtp_address'] = "${SMTP_ADDRESS}"
        gitlab_rails['smtp_port'] = ${SMTP_PORT}
        gitlab_rails['smtp_user_name'] = "${SMTP_USER}"
        gitlab_rails['smtp_password'] = "${SMTP_PASSWORD}"
        gitlab_rails['smtp_domain'] = "${SMTP_DOMAIN}"
        # Authentication: 'login', 'plain', or 'cram_md5'
        gitlab_rails['smtp_authentication'] = "${SMTP_AUTH}"
        # If your SMTP server supports STARTTLS
        gitlab_rails['smtp_enable_starttls_auto'] = ${SMTP_STARTTLS}
        # If you need TLS over port 465, set this to 'true' and adjust your SMTP_PORT
        gitlab_rails['smtp_tls'] = ${SMTP_TLS}
        # Sender and Reply-To addresses
        gitlab_rails['gitlab_email_from'] = "${SMTP_FROM}"
        gitlab_rails['gitlab_email_reply_to'] = "${SMTP_REPLY_TO}"
    networks:
      - '${TRAEFIK_NETWORK}'
    ports:
      - '2222:22'
    volumes:
      - '${GITLAB_PERSISTENCE}/config:/etc/gitlab'
      - '${GITLAB_PERSISTENCE}/logs:/var/log/gitlab'
      - '${GITLAB_PERSISTENCE}/data:/var/opt/gitlab'
    shm_size: '${GITLAB_SHM_SIZE}'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`${GITLAB_HOSTNAME}`)"
      - "traefik.http.routers.gitlab.entrypoints=websecure"
      - "traefik.http.routers.gitlab.tls=true"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"